# Generated by Django 4.2.7 on 2024-05-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_remove_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(default='123456', max_length=10, unique=True),
        ),
    ]
